In [1]:
import numpy as np
import pandas as pd

In [60]:
train_data = pd.read_csv('./train.csv', index_col="PassengerId")

In [61]:


columns_of_X = [u'Pclass','Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [111]:
def data_clean(data):
    columns_of_X = [u'Pclass','Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
    X = data[columns_of_X]
    X['Sex'].replace({'male':1, 'female':0}, inplace=True)
    X['Age'].fillna(0, inplace=True) # 将Age中的NaN转换为0
    X['Embarked'].replace({
        'S': 0,
        'C': 1,
        'Q': 2,
        np.nan: 3
    }, inplace=True)
    X.fillna(0,inplace=True)
    X.applymap(lambda x: int(x))
    return X

train_X = data_clean(train_data)

/Users/abnerzheng/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2705: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [103]:
train_Y = train_data['Survived']

In [104]:
from sklearn import tree

In [105]:
clf = tree.DecisionTreeClassifier()

In [106]:
clf.fit(train_X,train_Y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [112]:
test_data = pd.read_csv('./test.csv', index_col='PassengerId')
test_X = data_clean(test_data)

In [113]:
test_X

             Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
PassengerId
892               3    1  34.5      0      0    7.8292         2
893               3    0  47.0      1      0    7.0000         0
894               2    1  62.0      0      0    9.6875         2
895               3    1  27.0      0      0    8.6625         0
896               3    0  22.0      1      1   12.2875         0
897               3    1  14.0      0      0    9.2250         0
898               3    0  30.0      0      0    7.6292         2
899               2    1  26.0      1      1   29.0000         0
900               3    0  18.0      0      0    7.2292         1
901               3    1  21.0      2      0   24.1500         0
902               3    1   0.0      0      0    7.8958         0
903               1    1  46.0      0      0   26.0000         0
904               1    0  23.0      1      0   82.2667         0
905               2    1  63.0      1      0   26.0000         0
906               1    0  47.0      1      0   61.1750         0
907               2    0  24.0      1      0   27.7208         1
908               2    1  35.0      0      0   12.3500         2
909               3    1  21.0      0      0    7.2250         1
910               3    0  27.0      1      0    7.9250         0
911               3    0  45.0      0      0    7.2250         1
912               1    1  55.0      1      0   59.4000         1
913               3    1   9.0      0      1    3.1708         0
914               1    0   0.0      0      0   31.6833         0
915               1    1  21.0      0      1   61.3792         1
916               1    0  48.0      1      3  262.3750         1
917               3    1  50.0      1      0   14.5000         0
918               1    0  22.0      0      1   61.9792         1
919               3    1  22.5      0      0    7.2250         1
920               1    1  41.0      0      0   30.5000         0
921               3    1   0.0      2      0   21.6792         1
...             ...  ...   ...    ...    ...       ...       ...
1280              3    1  21.0      0      0    7.7500         2
1281              3    1   6.0      3      1   21.0750         0
1282              1    1  23.0      0      0   93.5000         0
1283              1    0  51.0      0      1   39.4000         0
1284              3    1  13.0      0      2   20.2500         0
1285              2    1  47.0      0      0   10.5000         0
1286              3    1  29.0      3      1   22.0250         0
1287              1    0  18.0      1      0   60.0000         0
1288              3    1  24.0      0      0    7.2500         2
1289              1    0  48.0      1      1   79.2000         1
1290              3    1  22.0      0      0    7.7750         0
1291              3    1  31.0      0      0    7.7333         2
1292              1    0  30.0      0      0  164.8667         0
1293              2    1  38.0      1      0   21.0000         0
1294              1    0  22.0      0      1   59.4000         1
1295              1    1  17.0      0      0   47.1000         0
1296              1    1  43.0      1      0   27.7208         1
1297              2    1  20.0      0      0   13.8625         1
1298              2    1  23.0      1      0   10.5000         0
1299              1    1  50.0      1      1  211.5000         1
1300              3    0   0.0      0      0    7.7208         2
1301              3    0   3.0      1      1   13.7750         0
1302              3    0   0.0      0      0    7.7500         2
1303              1    0  37.0      1      0   90.0000         2
1304              3    0  28.0      0      0    7.7750         0
1305              3    1   0.0      0      0    8.0500         0
1306              1    0  39.0      0      0  108.9000         1
1307              3    1  38.5      0      0    7.2500         0
1308              3    1   0.0      0      0    8.0500         0
1309              3    1   0.0      1      1   22.3583         1

[418 rows x 7 columns]

In [116]:
predict_y = clf.predict(test_X)

In [118]:
predict_y

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1])

In [120]:
result = pd.DataFrame(data=predict_y, index=range(892, 1310))

In [124]:
result.to_csv('my_result.csv', index_label=['PassengerId','Survived'])

In [125]:
validation_Y = clf.predict(train_X)

In [126]:
validation_Y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [127]:
train_Y

PassengerId
1      0
2      1
3      1
4      1
5      0
6      0
7      0
8      0
9      1
10     1
11     1
12     1
13     0
14     0
15     0
16     1
17     0
18     1
19     0
20     1
21     0
22     1
23     1
24     1
25     0
26     1
27     0
28     0
29     1
30     0
      ..
862    0
863    1
864    0
865    0
866    1
867    1
868    0
869    0
870    1
871    0
872    1
873    0
874    0
875    1
876    1
877    0
878    0
879    0
880    1
881    1
882    0
883    0
884    0
885    0
886    0
887    0
888    1
889    0
890    1
891    0
Name: Survived, dtype: int64

In [137]:
1- 1.0*(train_Y - validation_Y).abs().sum() / len(train_Y)

0.9820426487093153

In [135]:
len(train_Y)

891